#!/usr/bin/env bash

usage="Usage: $0 [-d dry run] [-h help] [-v verbose] MASTER_PATH DUPLICATES_PATH..."
dryrun="false"
verbose="false"

while getopts ":dv" opt; do
	case $opt in
		d) dryrun="true";;
		v) verbose="true";;
		h) echo ${usage}; exit 0;;
		\?) echo ${usage}; exit 1;;
	esac
done
shift $(( OPTIND - 1 ))

[[ "$#" -gt 1 ]] || { echo ${usage} && exit 1 ; }

tmp=$(mktemp -d)
trap "rm -Rf ${tmp}" EXIT
echo "Using tmp dir ${tmp}"

master=$1; shift
master_md5s="${tmp}/master.md5s"
dup_md5s="${tmp}/dups.md5s"
dup_count=0
rm_count=0
uniq_count=0

function makeHashes() {
	local path=$1
	local stdout=$2
	[[ -e "${path}" ]] || { echo "Directory ${path} doesn't exist" && exit 1 ; }
	local abs_path=$(readlink -e "$path") || { echo "Failed to readlink ${path}" && exit 1 ; }
	echo "${abs_path}" >> ${tmp}/abs_paths

	[[ $(grep "${abs_path}" ${tmp}/abs_paths | wc -l) == 1 ]] || { echo "Master path and duplicate(s) path are the same!" && exit 1; }

	echo "Generating hashes for ${path} into ${stdout}"
	which parallel &>/dev/null || { echo "Failed to find gnu parallel on PATH, is it installed??" && exit 1 ; }
	which md5sum &>/dev/null && 
		find "${path}" -type f | parallel --jobs +2 --eta md5sum {} 1> "${stdout}" 2>/dev/null ||
		find "${path}" -type f | parallel --jobs +2 --eta md5 -r {} 1> "${stdout}" 2>/dev/null
	[[ $(cat "${stdout}" | wc -l) -gt 0 ]] || { echo "Created no hashes, aborting, this doesn't seem right" && exit 1 ; }		
	echo "Total files in '${path}' == $(cat "${stdout}" | wc -l)"
}
function duplicate() {	
	local dup=$1
	local master=$2
	
	let dup_count+=1
	if [[ "${dryrun}" == "false" ]]; then
		 let rm_count+=1
		 rm "${dup}"
	fi		 		
	if [[ "${verbose}" == "true" ]]; then echo "removed ${dup} as duplicate of ${master}"; fi
}
function unqiue() {	let uniq_count+=1; }

makeHashes "${master}" "${master_md5s}" || exit 1

while (( "$#" )); do
	duplicates=$1; shift	
	makeHashes "${duplicates}" "${dup_md5s}" || exit 1
	
	while read i; do 
		hash="$(echo "$i" | cut -d ' ' -f 1)"
		file="$(echo "$i" | sed -e "s/${hash}[[:space:]]*//")"
		match="$(grep -P "^${hash}\s.*$" "${master_md5s}")"
		[[ $? == "0" ]] \
			&& duplicate "${file}" "$(echo "${match}" | sed -e "s/${hash}[[:space:]]*//")" \
			|| unqiue "${file}"
	done < "${dup_md5s}"
done

msg="Total files processed = $[dup_count + uniq_count], duplicates = ${dup_count}, unique files = ${uniq_count}, removed = ${rm_count}"
[[ "${dryrun}" == "true" ]] && msg="${msg} (dry run)"
echo "${msg}"

